constants:
    probdir: data/probsets/vpexp1
    output: mongodb://central.senbazuru.soe.cranfield.ac.uk/vp2013/vpexp1
    num_bins: 512

parametersets:

    problems:
        array: file:oa.64.6.4.3.txt
        parameters:
            num_items:
                values: [ 2000, 3000, 4000, 5000 ]

            num_dims:
                values: [ 1, 2, 3, 4 ]
               
            slack:
                values: [ 0.2, 0.4, 0.6, 0.8 ]

            cov:
                values: [ 0.00, 0.33, 0.66, 1.00 ]

            # yes, split is an algorithm parameter, but don't want to multiply
            # whole thing x another 5 or more...
            
            split:
                values: [ 1, 2, 4, 8 ]

        variables:
            - name: 'prefix'
              value: prob-seed:%(index)s-num_bins:%(num_bins)s-num_items:%(num_items)s-num_dims:%(num_dims)s-cov:%(cov)s-slack:%(slack)s

            - name: 'probfile'
              value: '%(prefix)s.prob'

    algorithms:
        array: full-factorial
        parameters:
            pack:
                values: [ 'pack_by_items', 'pack_by_bins' ]

            select:
                values: [ 'none', 'a:sum', 'd:sum', 'a:max', 'd:max', 
                          'a:maxdiff', 'd:maxdiff', 'a:maxratio', 'd:maxratio', 
                          'a:lnorm', 'd:lnorm', 
                          'pp', 'pp:w=2', 'cp:w=1', 'cp:w=2' ]

            isort:
                values: [ 'none', 'a:sum', 'd:sum', 'a:max', 'd:max', 
                          'a:maxdiff', 'd:maxdiff', 'a:maxratio', 'd:maxratio', 
                          'a:lnorm', 'd:lnorm' ]

            bsort:
                values: [ 'none', 'a:sum', 'd:sum', 'a:max', 'd:max', 
                          'a:maxdiff', 'd:maxdiff', 'a:maxratio', 'd:maxratio', 
                          'a:lnorm', 'd:lnorm' ]

commandsets:
    - parametersets: [ 'problems' ]
      commands:
        - generate-vectorpack-problem -s %(index)s -b %(num_bins)s -i %(num_items)s -d %(num_dims)s -c %(cov)s -k %(slack)s > %(probdir)s/%(probfile)s

    - parametersets: [ 'problems', 'algorithms' ]
      commands:
        - pack-vectors -i %(probdir)s/%(probfile)s -P %(pack)s -I %(isort)s -B %(bsort)s -S %(select)s -s %(split)s -o %(output)s

